if (app_lib.txnId() == null) {
    // Get current date and time
    var currDate = moment().format('YYYY-MM-DD');
    var currTime = moment().format('HH:mm:ss');
    // Set current date for the "Created_By_Date" field if it exists
    if (fields["Created_By_Date"]) {
        fields["Created_By_Date"].value = currDate;
    }

}


app_lib.hideField([
    "Preferred_Name",
    "Availability_Type",
    "Availability_Details",
    "Transfer_Capability",
    "MONDAY_AM",
    "MONDAY_PM",
    "MONDAY_NOC",
    "TUESDAY_AM",
    "TUESDAY_PM",
    "TUESDAY_NOC",
    "WEDNESDAY_AM",
    "WEDNESDAY_PM",
    "WEDNESDAY_NOC",
    "THURSDAY_AM",
    "THURSDAY_PM",
    "THURSDAY_NOC",
    "FRIDAY_AM",
    "FRIDAY_PM",
    "FRIDAY_NOC",
    "SATURDAY_AM",
    "SATURDAY_PM",
    "SATURDAY_NOC",
    "SUNDAY_AM",
    "SUNDAY_PM",
    "SUNDAY_NOC",
    "Weight_Class",
    "Lift_Capacity_Class",
    "Exclusion_Never_Client_IDs",
    "Exclusion_Avoid_Client_IDs",
    "Max_Weekly_Hours",
    "Target_Weekly_Hours",
    "Driver_License_",
    "Has_Car_",
    "Timezone",
    "Time",
    "LastMinute_Ready_Ghost_Pool_",
    "Reliability_Score_0100",
    "Personality_Match",
    "Physical_Capability_lbs",
    "System_Information",
    "Created_By",
    "Last_Modified_By",
    "Last_Modified_At_Location",
    "Physical_Capability_lbs",
    "Personality_Match",
    "Location",
    "Employee_Details",
    "Caregiver_Details",
    "Profile_Picture",
    "First_Name",
    "Middle_Name",
    "Last_Name",
    "Gender",
    "Email",
    "Role",
    "Address",
    "Caregiver_Agreement_Details",
    "Facility",
    "Private",
    "Shift_Details",
    "Additional_Shifts",
    "Max_Hours",
    "Min_Hours",
    "Personal_Information",
    "Office",
    "SSN",
    "Salutation",
    "User_Name",
    "Alternate_Email",
    "Date_of_Birth",
    "Marital_status",
    "Race",
    "Suffix",
    "Caregiver_Type",
    "State_ID",
    "Caregiver_License_Number",
    "Caregiver_Medicaid_ID",
    "Hire_Date",
    "WOTC_Status",
    "Address_Information",
    "Alternate_Address",
    "ZipPostal_Code",
    "City",
    "State",
    "Country",
    "Contact_Details",
    "Primary",
    "Time_Tracking",
    "Phone_Type",
    "Caregiver_Phone_Number",
    "Notes",
    "Emergency_Contact",
    "Full_Name",
    "Email_Address",
    "Relation",
    "Mobile_Number",
    "Note",
    "Referral_Sources",
    "Referred_By",
    "Referral_Date",
    "Referral_Notes",
    "Summary_Notes",
    "Skills_Experience",
    "Date_of_Hire",
    "Experience",
    "Skill_Type",
    "Availability",
    "Cooking_Skills",
    "General",
    "Language",
    "Level_of_Ability",
    "Personal_Care",
    "Pets",
    "Transportation",
    "Vehicle_Type",
    "Pet_Restriction",
    "Smoking_Restriction",
    "Additional_Information",
    "Caregiver_Preferences",
    "Exempt_From_Holiday_Pay_Calculation",
    "Distance_Willing_to_Travel",
    "Miscellaneous_Details",
    "Medical_Information"
]);


if (fields["Employment_Type"].value == "Employee") {
    app_lib.showField([
        "Employee_Details",
        "Profile_Picture",
        "First_Name",
        "Middle_Name",
        "Last_Name",
        "Gender",
        "Email",
        "Role",
        "Address",
        "System_Information",
        "Created_By",
        "Last_Modified_By",
        "Last_Modified_At_Location",
        "User_Name"
    ]);
}

if (fields["Employment_Type"].value == "Caregiver") {
    app_lib.showField([
        "Preferred_Name",
        "Availability_Type",
        "Transfer_Capability",
        "Weight_Class",
        "Lift_Capacity_Class",
        "Exclusion_Never_Client_IDs",
        "Exclusion_Avoid_Client_IDs",
        "Max_Weekly_Hours",
        "Target_Weekly_Hours",
        "Driver_License_",
        "Has_Car_",
        "Timezone",
        "Time",
        "LastMinute_Ready_Ghost_Pool_",
        "Reliability_Score_0100",
        "Personality_Match",
        "Physical_Capability_lbs",
        "System_Information",
        "Created_By",
        "Last_Modified_By",
        "Last_Modified_At_Location",
        "Physical_Capability_lbs",
        "Personality_Match",
        "Location",
        "Caregiver_Details",
        "Profile_Picture",
        "First_Name",
        "Middle_Name",
        "Last_Name",
        "Gender",
        "Email",
        "Role",
        "Address",
        "Caregiver_Agreement_Details",
        "Facility",
        "Private",
        "Additional_Shifts",
        "Max_Hours",
        "Min_Hours",
        "Personal_Information",
        "Office",
        "SSN",
        "Salutation",
        "User_Name",
        "Alternate_Email",
        "Date_of_Birth",
        "Marital_status",
        "Race",
        "Suffix",
        "Caregiver_Type",
        "State_ID",
        "Caregiver_License_Number",
        "Caregiver_Medicaid_ID",
        "Hire_Date",
        "WOTC_Status",
        "Address_Information",
        "Alternate_Address",
        "ZipPostal_Code",
        "City",
        "State",
        "Country",
        "Contact_Details",
        "Primary",
        "Time_Tracking",
        "Phone_Type",
        "Caregiver_Phone_Number",
        "Notes",
        "Emergency_Contact",
        "Full_Name",
        "Email_Address",
        "Relation",
        "Mobile_Number",
        "Note",
        "Referral_Sources",
        "Referred_By",
        "Referral_Date",
        "Referral_Notes",
        "Summary_Notes",
        "Skills_Experience",
        "Date_of_Hire",
        "Experience",
        "Skill_Type",
        "Availability",
        "Cooking_Skills",
        "General",
        "Language",
        "Level_of_Ability",
        "Personal_Care",
        "Pets",
        "Transportation",
        "Vehicle_Type",
        "Pet_Restriction",
        "Smoking_Restriction",
        "Additional_Information",
        "Caregiver_Preferences",
        "Exempt_From_Holiday_Pay_Calculation",
        "Distance_Willing_to_Travel",
        "Miscellaneous_Details",
        "Medical_Information"
    ]);
}

if (fields["Employment_Type"].value == "Caregiver" && fields["Availability_Type"].value == "AM, PM, NOC") {
    app_lib.showField([
        "Shift_Details",
        "MONDAY_AM",
        "MONDAY_PM",
        "MONDAY_NOC",
        "TUESDAY_AM",
        "TUESDAY_PM",
        "TUESDAY_NOC",
        "WEDNESDAY_AM",
        "WEDNESDAY_PM",
        "WEDNESDAY_NOC",
        "THURSDAY_AM",
        "THURSDAY_PM",
        "THURSDAY_NOC",
        "FRIDAY_AM",
        "FRIDAY_PM",
        "FRIDAY_NOC",
        "SATURDAY_AM",
        "SATURDAY_PM",
        "SATURDAY_NOC",
        "SUNDAY_AM",
        "SUNDAY_PM",
        "SUNDAY_NOC",
    ]);
}

if (fields["Employment_Type"].value == "Caregiver" && fields["Availability_Type"].value == "Custom Time") {
    app_lib.showField([
        "Shift_Details",
        "Availability_Details",
    ]);
}

var options = {
    timeZone: "America/Los_Angeles",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
};

var laTime = new Date().toLocaleString("en-US", options);

// Set to your field
fields["Time"].value = laTime;